import './globals.css'
import Footer from './components/ui/Footer'
import Header from './components/ui/Header'
import { roboto400 } from './fonts'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" className="">
            <body className={`h-screen ${roboto400.className}`}>
                <div className="flex flex-col h-full container mx-auto">
                    {/* <div className="grid grid-rows-3  container mx-auto"> */}
                    <div className=" ">
                        <Header />
                    </div>
                    <main className="flex flex-col grow">{children}</main>
                    <div className=" ">
                        <Footer />
                    </div>
                </div>
            </body>
        </html>
    )
}
